### ISSUE TITLE
Implications of adding id/pk field to _statements tables?

### ISSUE THREAD

**Issue by aaronhelton** [RDFLib/rdflib-sqlalchemy#14]
In my fork I set the SQLAlchemy table definitions to include id fields as primary keys in the four _statements tables. Is there any reason you can think of that this might break, either in this store plugin or in rdflib more generally? So far I am seeing no issue. I included it because I want to build a Django admin interface directly on the SQLAlchemy store in pursuit of some other goals.

**Comment by gjhiggins** [comment]
I replicated your changes in an “idkey” branch: 0076076. The changes cause some tests to fail. Travis CI should run the tests for that branch, just in case you can spot a solution.

**Comment by aaronhelton** [comment]
Take a look at https://github.com/aaronhelton/rdflib-sqlalchemy/commit/c418f363337e1b68287a8a255a22a23e93f2a97d for a potential solution. The tests were failing because the unionSELECT function for type assertions lacked the id column, whereas non-type assertions included it automatically. I also had to make sure it appeared in the extractTriple function and SQLAlchemy.triples, which calls it.

**Comment by gjhiggins** [comment]
Works for me, so I integrated your code, adding some necessary switches to handle existing dbs sans id fields. All tests pass but the id feature doesn't yet have tests. I fumbled in committing it to master instead of the branch, ideally, I'd have double-checked the backwards compat situation before committing but I don't have any legacy dbs from this plugin to use.

**Comment by adamhadani** [comment]
closing this issue, as far as i can tell all statement tables have an id field as primary key now, LMK if I missed something @aaronhelton
