### ISSUE TITLE
What is the license for this repo? Can you add a LICENSE file?

### ISSUE THREAD

**Issue by wondersmiths** [RDFLib/rdflib-sqlalchemy#68]

**Comment by mwatts15** [comment]
Pretty sure it's meant to be the BSD license since that's what it says in the README and setup.py. That said, there are multiple contributors who could conceivably assert copyright over parts of the code, and I doubt they all signed a "contributor license agreement" or "developer certificate of ownership" (I know I didn't).

@gjhiggins, @adamhadani : I would guess that the thing to do would be to ask all contributors to assert a copyright claim on their contributions and agree to the BSD license. Obviously, I am not a lawyer, but that seems like the minimum you'd want if you wanted to use rdflib-sqlalchemy in something. Sounds good?

**Comment by wondersmiths** [comment]
Thank you for your reply! It will be better to have the LICENSE file in the repository. BSD has different versions. Will you use the same term as RDFLib? https://github.com/RDFLib/rdflib/blob/master/LICENSE

**Comment by ghost** [comment]
FTR, historically, this was something of an _ad hoc_ contribution, it was floated as a sort of replacement for the old RDFLib 3 interface to Ian Bicking's SQLObject, this latter having gone out of scope a long time ago. IIRC there was little interest at the time and I just let it lie. Then Adam picked it up and spent quite a lot of effort breathing some life back into it.
What's required for the “assert a copyright claim on their contributions and agree to the BSD license”? FWIW, I agree with wondersmith's suggestion of adding the RDFLib licence.

**Comment by mwatts15** [comment]
@gjhiggins I refer back to that thing about me not being a lawyer, but I was thinking that it would be good to have the main developers just agree that they knowingly release the code they wrote under the BSD license. I guess there doesn't need to be an affirmative *claim* of ownership, but typically you'll see something like a list of authors in the copyright line in the license file.

@wondersmiths I mean the 3-clause BSD license, same as the main RDFLib lib up to a change in copyright holder names.

IDK if @adamhadani cares anymore. I'll make a LICENSE file, list y'all as copyright holders and make a PR. I'll leave it open until the weekend, so if anyone has a problem, they can speak up; otherwise, I'll merge it this weekend.

**Comment by ghost** [comment]
Oh okay. According to the RDFLib licence, the magic words are:
```
Copyright (c) 2002-2020, RDFLib Team
See CONTRIBUTORS and http://github.com/RDFLib/rdflib
All rights reserved.
```
and
```
Neither the name of Daniel Krech
```
So I guess just changing the URL from rdflib to rdflib-sqlalchemy, changing "Daniel Krech" to "Graham Higgins" (to avoid taking Dan's name in vain) and adding a CONTRIBUTORS file would suffice. On second thoughts, I suspect that the key association with Dan Krech is the "RDFLib" name, so ignore my suggestion above, just leave the reference to Dan as is.

**Comment by mwatts15** [comment]
There's already a CONTRIBUTORS.md. I just changed the "Neither the name of..." part back to "the copyright holder" from the template on  opensource.org
