### ISSUE TITLE
When does a transaction start?

### ISSUE THREAD

**Issue by bazile-clyde** [RDFLib/rdflib-sqlalchemy#89]
Does calling the `add` or `addN` method always start a transaction? If not, how do you start one? If so, does that mean nothing will be written to the DB unless `commit` is called? Also (if so), is there a way to avoid transactions?

```
SQLALCHEMY_PATH = "a/valid/path"
store = plugin.get("SQLAlchemy", Store)()

graph = Graph(store)
graph.open(SQLALCHEMY_URL, create=False)

# (...) add some triples with graph.add(triple_or_quad)

graph.commit()  # what if this wasnt here?
graph.close()
```

**Comment by mwatts15** [comment]
A transaction is committed in all of the methods. We call `Engine.begin()` and pass to a context manager.

We use the 1.4 "legacy" API where the, now deprecated, nesting of `begin()`/`commit()` is possible.  So, you can get the SQLArchemy engine from the store (or you could have passed it in to the Store's `__init__`) and call `begin()` around whatever calls to the store you want. So that changes the transaction boundary.

I think by "avoiding" transactions you mean not calling `commit()` within the transaction within the Store methods. (My understanding of the Python DB API is that you start a transaction when you execute anything if there isn't already one in progress.) Honestly, I prefer not actually managing the transaction within the store since it becomes complicated to manage when you need the transaction boundary to be broader than the Store can manage (e.g., committing after formatting a response to a web request). I haven't taken up that change since I became maintainer, but, as always, PRs with tests are welcome.

The `SQLAlchemy` store doesn't implement `commit()`, so it doesn't do anything if you call it.

SQLAlchemy transactions reference: https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=connect#using-transactions
